# Netlify configuration for React frontend
[build]
  base = "client"
  publish = "build"
  command = "CI=false npm run build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  NODE_ENV = "production"
  # Force the frontend to use relative paths for API calls
  REACT_APP_API_BASE = "/api"
  REACT_APP_NAME = "Crossover Helpdesk"

# Proxy API requests to the backend server (MUST come before catch-all)
[[redirects]]
  from = "/api/*"
  to = "https://crossover-helpdesk.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Redirect all other routes to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
